Repository CMPN-CODECELL/Hacktoberfest2020, pull requests merged in 2020-10, with the labels that each got.

#24 create Prime Sieve algorithm
  Algorithms/C++/Fibonacci/Fibonacci.cpp
  Algorithms/C++/Prime Number Sieve/prime_sieve.cpp
Labels: beginner, good first issue, hacktoberfest, hacktoberfest-accepted

#23 Implemented stack using array in C
  Data Structures/C/Queue(Array)/queue_array.c
  Data Structures/C/Stack (Array)/stack_array.c
Labels: beginner, good first issue, hacktoberfest

#31 First_Occurence
  Algorithms/C++/First_Occurence of element in sorted array/First_Occurence of given element in sorted array.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#37 Deployment Steps for streamlit
  .DS_Store
  Projects/.DS_Store
  Projects/streamlit/.DS_Store
  Projects/streamlit/Heroku Deployment of Streamlit.md
Labels: hacktoberfest-accepted

#42 added BFS code and updated README.md
  Algorithms/C++/BFS/BFS.cpp
  Algorithms/C++/BFS/README.md
Labels: hacktoberfest-accepted

#29 Api added
  Web Development/API/.gitignore
  Web Development/API/Procfile
  Web Development/API/app.py
  Web Development/API/issues.csv
  Web Development/API/pulls.csv
  Web Development/API/requirements.txt
  Web Development/API/spiders/__init__.py
  Web Development/API/spiders/__pycache__/__init__.cpython-37.pyc
  Web Development/API/spiders/__pycache__/issues.cpython-37.pyc
  Web Development/API/spiders/__pycache__/pr.cpython-37.pyc
  Web Development/API/spiders/__pycache__/repo.cpython-37.pyc
  Web Development/API/spiders/issues.py
  Web Development/API/spiders/pr.py
  requirements.txt
Labels: hacktoberfest-accepted

#54 Implemented linked list in C
  Data Structures/C/Linked List/LinkedList.c
Labels: hacktoberfest-accepted

#53 implemented stack using linklist
  Data Structures/C/Stack(Linked List)/stack_linklist
Labels: hacktoberfest-accepted

#52 Py_Deque
  Data Structures/Python/Queue/dqueue.py
  Data Structures/Python/Stack/stack.py
Labels: hacktoberfest-accepted

#43 Py_bubbleSort
  Algorithms/Sorting/bubbleSort.py
Labels: hacktoberfest-accepted

#28 Agario game
  Projects/Games/AgarioClone/LICENSE
  Projects/Games/AgarioClone/README.md
  Projects/Games/AgarioClone/client/index.html
  Projects/Games/AgarioClone/client/js/game.js
  Projects/Games/AgarioClone/client/js/models.js
  Projects/Games/AgarioClone/server/.gitignore
  Projects/Games/AgarioClone/server/pom.xml
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/GameEndpoint.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/config/GameConfig.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/Point.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/communicator/Communicator.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/communicator/impl/CallbackCommunicator.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/communicator/impl/SessionCommunicator.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/enums/EventType.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/game/GameField.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/game/MobsManager.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/game/Person.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/message/Message.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/message/MessageDecoder.java
  Projects/Games/AgarioClone/server/src/main/java/men/brakh/agario/model/message/MessageEncoder.java
  Projects/Games/AgarioClone/server/src/main/resources/game.properties
  Projects/Games/AgarioClone/server/src/main/resources/log4j.properties
  Projects/Games/AgarioClone/server/src/test/java/men/brakh/agario/model/game/GameFieldTest.java
Labels: hacktoberfest-accepted

#27 Hash map in C
  Data Structures/C/Hash Map/README.md
  Data Structures/C/Hash Map/hash_map.c
  Data Structures/C/Hash Map/hash_map.h
Labels: hacktoberfest-accepted

#26 BST in C
  Data Structures/C/Binary Search Tree/README.md
  Data Structures/C/Binary Search Tree/bst.c
  Data Structures/C/Binary Search Tree/bst.h
Labels: hacktoberfest-accepted

#80 Implemented ML algos on the Iris Dataset
  Machine Learning Problem-Statements/Iris/Iris_Dataset_Machine_Learning.ipynb
Labels: hacktoberfest-accepted

#82 added a machine learning model named customer journey.
  Machine Learning Projects/Customer_journey/Customer_Journey.ipynb
  Machine Learning Projects/Customer_journey/Readme.md
Labels: hacktoberfest-accepted

#75 Create PriorityQueue.cpp
  Data Structures/C++/Priority Queue/PriorityQueue.cpp
Labels: hacktoberfest-accepted

#79 PROJECT - PACMAN GAME
  Pacman Game in C/Pacman/Pacman Game in C.exe
  Pacman Game in C/Pacman/SDL.dll
  Pacman Game in C/Pacman/SDL_image.dll
  Pacman Game in C/Pacman/accessories.c
  Pacman Game in C/Pacman/bin/Debug/Pacman Game in C.exe
  Pacman Game in C/Pacman/borders.psd
  Pacman Game in C/Pacman/header.h
  Pacman Game in C/Pacman/jpeg.dll
  Pacman Game in C/Pacman/main.c
  Pacman Game in C/Pacman/map.c
  Pacman Game in C/Pacman/move_guide.c
  Pacman Game in C/Pacman/obj/Debug/accessories.o
  Pacman Game in C/Pacman/obj/Debug/main.o
  Pacman Game in C/Pacman/obj/Debug/map.o
  Pacman Game in C/Pacman/obj/Debug/move_guide.o
  Pacman Game in C/Pacman/obj/Debug/resource.res
  Pacman Game in C/Pacman/pacman.ico
  Pacman Game in C/Pacman/pacman.png
  Pacman Game in C/Pacman/pacman_128X128.ico
  Pacman Game in C/Pacman/pacman_16X16.png
  Pacman Game in C/Pacman/pacman_c.cbp
  Pacman Game in C/Pacman/pacman_c.depend
  Pacman Game in C/Pacman/pacman_c.layout
  Pacman Game in C/Pacman/resource.rc
  Pacman Game in C/Pacman/sprite.psd
  Pacman Game in C/Pacman/sprites/Thumbs.db
  Pacman Game in C/Pacman/sprites/borders.gif
  Pacman Game in C/Pacman/sprites/builder_cursor.gif
  Pacman Game in C/Pacman/sprites/builder_cursor_follow.gif
  Pacman Game in C/Pacman/sprites/dark.jpg
  Pacman Game in C/Pacman/sprites/pacman.gif
  Pacman Game in C/Pacman/sprites/pacman_follow.gif
  Pacman Game in C/Pacman/sprites/tick_mark.gif
  Pacman Game in C/Pacman/temp.lvl
  Pacman Game in C/Readme.docx
Labels: hacktoberfest-accepted

#77 Tetris Game using Python
  Projects/Games/TetrisGame/1.jpeg
  Projects/Games/TetrisGame/Board.py
Labels: hacktoberfest-accepted

#81 Added TitanicSurvivorChallenge in ML Projects
  Machine Learning Projects/Titanic Survivor Challenge-using Decision Trees/.ipynb_checkpoints/Untitled-checkpoint.ipynb
  Machine Learning Projects/Titanic Survivor Challenge-using Decision Trees/TitanicSurvivorchallenge.ipynb
  Machine Learning Projects/Titanic Survivor Challenge-using Decision Trees/test.csv
  Machine Learning Projects/Titanic Survivor Challenge-using Decision Trees/train.csv
Labels: hacktoberfest-accepted
